### ISSUE TITLE
differential read 0-2

### ISSUE THREAD

**Issue by ramarro123** [adafruit/Adafruit_ADS1X15#24]
Hi,

why there is differential read 01 and 23 but not 02 for instance?

**Comment by soligen2010** [comment]
When it comes to open source software, asking "why isn't this done" has an answer of "because whoever wrote it didn't need it, or didn't feel like doing it" or "because it isn't possible".  

In this case both answers apply.  02 is not a valid combination - the chip simply cant do it. You would have to ask TI why, but it is a pointless question to ask - just design your circuit in accordance with the data sheet, or choose a different chip if that is not possible. Same with the library - design within it's capabilities, or enhance it, or write your own.

The other answer is because Adafriut didn't see a need to support all the features of the chip.  They did enough to be able to sell their product, but are not in the business of providing complete driver libraries - nor do they enhance them along the way.  They did enough to be able to sell the device, but no more.

Look around a little bit and you will find more complete libraries - like the soligen2010 fork of this this library.  This still may not support all features of the chip, but that's the beauty of open source - you are free to make a copy and add on what you need.
