### ISSUE TITLE
Add ability to configure Data Rate

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_ADS1X15#56]
Re this thread:
https://forums.adafruit.com/viewtopic.php?f=19&t=175501

Add ability to configure Data Rate? i.e, the DRx bits in the Config Register. Looks like things are currently hard wired to a single value.

**Comment by caternuson** [comment]
Added with #59

**Comment by Russell108** [comment]
Calling this function data rate is not intuitive Why not call it sample rate well I am assuming this is what is being configured

**Comment by Russell108** [comment]
I Believe I have realised this library has a  limitation

evet though the data rate is changed, it does little to speed up the delivery of data to the Arduino

Since it uses a time rather than the alarm to check if data is available to read

In my opinion, this makes the library very ineffective in real terms. 

This library does a better job. https://github.com/jrowberg/i2cdevlib
